# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, default='settings.MEDIA_ROOT/img/default.jpg', null=True, upload_to=''),
        ),
    ]
